-- TIRANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS SE EXISTIR
DROP DATABASE IF EXISTS DBEXERCICIO08;

-- CRIANDO A BASE DE DADOS;
CREATE DATABASE DBEXERCICIO08;

-- ACESSANDO A BASE DE DADOS;
USE DBEXERCICIO08;

-- 2. Crie o SCRIPT de criação do banco de dados
CREATE TABLE LIVROS (
	IDLIVROS INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(180) NOT NULL
    , AUTOR VARCHAR(180) NOT NULL
    , EDITORA VARCHAR(120) NOT NULL
    , ANOPUBLICACAO INT NOT NULL
    , PRIMARY KEY (IDLIVROS)
    );
    
-- 3. Insira pelo menor 4 registro (Insert)
INSERT INTO LIVROS (TITULO, AUTOR, EDITORA, ANOPUBLICACAO) VALUES
('HAMLET', 'WILLIAM SHAKESPEARE', 'ABRIL', 2010),
('CAIM', 'JOSE SARAMAGO', 'CIA DAS LETRAS', 1996),
('ODES', 'PABLO NERUDA', 'SEXTANTE', 2000),
('FLORES', 'FERNANDO PESSOA', 'ROCCO', 2015);

-- 4. Liste os dados da tabela (Select)
SELECT * FROM LIVROS;

-- 5. Altere 2 registro usando alguma condição que não seja a PK (Update)
UPDATE LIVROS SET EDITORA = 'RECORD' WHERE TITULO = 'CAIM';
UPDATE LIVROS SET ANOPUBLICACAO = 2013 WHERE EDITORA = 'SEXTANTE';

-- 6. Delete 1 registros usando alguma codição que não seja a PK (Delete)
DELETE FROM LIVROS WHERE AUTOR = 'JOSE SARAMAGO';