-- TIRANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO05;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO05;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO05;

-- 2. Crie o SCRIPT de criação do banco de dados
CREATE TABLE PRAIAS (
	IDPRAIAS INT NOT NULL AUTO_INCREMENT
    , PRAIA VARCHAR(120) NOT NULL
    , LOCALIZACAO VARCHAR(120) NOT NULL
    , PONTO INT NOT NULL
    , DATA_COL DATE NOT NULL
    , SITUACAO VARCHAR (45) NOT NULL
    , PRIMARY KEY (IDPRAIAS)
);
-- 3. Insira pelo menos 4 linhas de dados da imagem na tabela (Insert)
INSERT INTO PRAIAS (PRAIA, LOCALIZACAO, PONTO, DATA_COL, SITUACAO) VALUES
('PRAIA DA BARRA DA LAGOA', 'APROXIMADAMENTE 50 METROS A ESQ. DOS MOLES', 32,'2024-01-30', 'PROPRIA'),
('PRAIA DA BARRA DA LAGOA', 'FTE RUA ACONCHEGO DO MAR', 88, '2024-01-30', 'PROPRIA'),
('PRAIA DA BASE AEREA', 'AO LADO DO TRAPICHE', 49, '2024-01-29', 'PROPRIA'),
('PRAIA DA BEIRA MAR NORTE', 'EM FRENTE AO MONUMENTO DA POLICIA MILITAR', 11, '2024-01-29', 'IMPROPRIA');
-- 4. Liste os dados da tabela e verifique se ficou conforme a imagem (Select)
SELECT * FROM PRAIAS;

-- 5. Altere a situação de todos os registros para próprio
UPDATE PRAIAS SET SITUACAO = 'PROPRIA' WHERE SITUACAO = 'IMPROPRIA';
    
-- 6. Altere a quantidade do produto coxinha da data do dia 07/01/2020 para 2
-- UPDATE PRODUTO SET QUANTIDADE = 2 WHERE PRODUTO = 'COXINHA' AND DATA_PROD = '2020-01-07';
    
-- 7. Apague todos os registro com data igual a 06/01/2020.
-- DELETE FROM PRODUTO WHERE DATA_PROD = '2020-01-06';