-- DESATIVANDO O MODO SEGURO
SET SQL_SAFE_UPDATES =0;

-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO09;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO09;

-- CONECTANDO NO BANCO DE DADOS
USE DBEXERCICIO09;

-- CRIANDO AS TABELAS
CREATE TABLE PESSOA (
IDPESSOA INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(120) NOT NULL
, DT_NASC DATE NOT NULL
, PRIMARY KEY (IDPESSOA)
);

CREATE TABLE CIN (
IDCIN INT NOT NULL AUTO_INCREMENT
, CPF VARCHAR(11) NOT NULL
, DT_EMISSAO DATE NOT NULL
, IDPESSOA INT NOT NULL UNIQUE
, PRIMARY KEY (IDCIN)
, FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA)
);

INSERT INTO PESSOA (NOME, DT_NASC)
VALUES ('ANDRE', '2020-01-01');

SELECT * FROM PESSOA;

INSERT INTO CIN (CPF, DT_EMISSAO, IDPESSOA)
VALUES ('4564689', '2025-04-14');

SELECT * FROM PESSOA;