-- TIRANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS SE EXIXTIR
DROP DATABASE IF EXISTS DBEXERCICIO11;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO11;

-- ACESSANDO O BANCO DE DADOS
USE DBEXERCICIO11;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120) NOT NULL
    , PRIMARY KEY (IDCLIENTE)
);
    
CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(50) NOT NULL
	, PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE RELACAO (
	IDPRODUTO INT NOT NULL
    , IDCLIENTE INT NOT NULL
    , PRIMARY KEY (IDPRODUTO, IDCLIENTE)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);