-- TIRANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO06;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO06;

-- CONECTANDO AO BANCO DE DADOS
USE DBEXERCICIO06;

-- 2. Crie o SCRIPT de criação do banco de dados
CREATE TABLE EXERCICIO01 (
		IDEXERCICIO01 INT NOT NULL AUTO_INCREMENT
        , IDALUNO INT NOT NULL
        , NOMEALUNO VARCHAR(120) NOT NULL
        , PRIMARY KEY (IDEXERCICIO01)
);

-- 3. Insira pelo menor 4 registro (Insert)
INSERT INTO EXERCICIO01 (IDALUNO, NOMEALUNO) VALUES
(012025, 'JOAO PAULO'),
(052025, 'MARIA CLARA'),
(092025, 'LUCAS SANTOS'),
(032025, 'THAYS BECKER');

-- 4. Liste os dados da tabela (Select)
SELECT * FROM EXERCICIO01;

-- 5. Altere 2 registro usando alguma condição que não seja a PK (Update)
UPDATE EXERCICIO01 SET NOMEALUNO = 'JOAO PEDRO' WHERE IDALUNO = 092025;

-- 6. Delete 1 registros usando alguma codição que não seja a PK (Delete)
DELETE FROM EXERCICIO01 WHERE IDALUNO = 032025;

SELECT * FROM EXERCICIO01;