-- TIRANDO O MODO SEGURO
SET SQL_SAFE_UPDATES = 0;

-- APAGANDO O BANCO DE DADOS, SE EXISTIR
DROP DATABASE IF EXISTS DBEXERCICIO10;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO10;

-- ACESSANDO O BANCO DE DADOS
USE DBEXERCICIO10;

-- CRIANDO AS TABELAS
CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(120)
    , PRIMARY KEY (IDCLIENTE)
    );
    
CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , DTEMISSAO DATE NOT NULL
    , PRODUTO VARCHAR(50) NOT NULL
    , QTD INT NOT NULL
    , IDCLIENTE INT NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
    );